name: GitHub CI

on:
  push:
    branches:
      - multiplatform
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ jdk11, jdk11-alpine, jdk11-focal, jdk17, jdk17-alpine, jdk17-focal, jdk17-graal, jdk17-focal-graal, jdk21, jdk21-alpine, jdk21-graal ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: gradle:${{ matrix.version }}

      - name: test
        env:
          version: ${{ matrix.version }}
          expectedGradleVersion: "8.7"
        run: |
          if [[ "${version}" =~ "graal" ]]; then
            cd test-graal
          else
            cd test
          fi
          ./run.sh "gradle:${version}" "${expectedGradleVersion}"
